name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Testa Compilação
      id: testa-compilacao
      uses: education/autograding-command-grader@v1
      with:
        test-name: Testa Compilação
        setup-command: ''
        command: cmake -B build && cmake --build build
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TESTA-COMPILACAO_RESULTS: "${{steps.testa-compilacao.outputs.result}}"
      with:
        runners: testa-compilacao
